sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.3
script:
  - sbt ++$TRAVIS_SCALA_VERSION scripted
after_success:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1485d094c1562a516328
    on_success: change
    on_failure: always
    on_start: false
