sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.3
script:
  - sbt ++$TRAVIS_SCALA_VERSION scripted
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1485d094c1562a516328
    on_success: change
    on_failure: always
    on_start: never
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
